# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
# - script: |
#     echo Install Az.* modules
#     Install-Module Az.Accounts -Scope CurrentUser -Force
#     Install-Module Az.Resources -Scope CurrentUser -Force
#   displayName: 'install az modules'

# - script: |
#     echo List available modules
#     gmo -list
#   displayName: 'list available modules'

- task: PowerShell@2
  inputs:
    filePath: '/azure-pipelines.ps1'
    pwsh: true



# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: '# Write your powershell commands here.
      
#       # Write-Host "Hello World"
#       Write-Host $(pwd)
#       Write-Host $psscriptroot
#       Install-Module "az.Accounts" -scope CurrentUser -Force
#       Install-Module "az.resources" -scope CurrentUser -Force
#       Write-Host $(gmo -List | out-string)

      
#       # Use the environment variables input below to pass secret variables to this script.'
#     pwsh: true
#     workingDirectory: 'd:\\a\\1\\s\\'

# - task: AzurePowerShell@4
#   inputs:
#     ScriptType: 'InlineScript'
#     azurePowerShellVersion: 'LatestVersion'

# - task: Pester Powershell unittest@2
#   inputs:
#     ItemSpec: 'Tests\*.tests.ps1'
#     FailOnError: true

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'NUnit'
#     testResultsFiles: '**/TEST-*.xml'

