# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- script: |
    echo Install Az.* modules
    Install-Module Az.Accounts -Scope CurrentUser -Force
    Install-Module Az.Resources -Scope CurrentUser -Force
  displayName: 'install az modules'

- script: |
    echo List available modules
    gmo -list
  displayName: 'list available modules'

- task: Pester Powershell unittest@2
  inputs:
    ItemSpec: 'Tests\*.tests.ps1'
    FailOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'