# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

pool:
  vmImage: 'windows-2019'

- task: Pester Powershell unittest@2
  inputs:
    ItemSpec: '*.tests.ps1'
    FailOnError: true

